# Generated by Django 3.1 on 2020-10-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbrewforyou_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
