# Generated by Django 3.1.2 on 2020-10-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microbrewforyou_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fav_breweries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_breweries', to='microbrewforyou_app.breweries'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fav_brewtypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_brewtypes', to='microbrewforyou_app.brewtypes'),
        ),
    ]
