# Generated by Django 3.1.2 on 2020-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbrewforyou_app', '0002_auto_20201006_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.TextField(choices=[('columbus', 'Columbus'), ('colorado springs', 'Colorado Springs'), ('carmel', 'Carmel')], max_length=240),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.TextField(choices=[('columbus', 'Columbus'), ('colorado springs', 'Colorado Springs'), ('carmel', 'Carmel')], max_length=240),
        ),
    ]
