# Generated by Django 3.1.2 on 2020-10-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microbrewforyou_app', '0003_auto_20201006_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
