# Generated by Django 3.1.2 on 2020-10-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbrewforyou_app', '0005_auto_20201007_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.TextField(choices=[('Columbus', 'Columbus'), ('Colorado_Springs', 'Colorado Springs'), ('Carmel', 'Carmel')], max_length=240),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.TextField(choices=[('Columbus', 'Columbus'), ('Colorado_Springs', 'Colorado Springs'), ('Carmel', 'Carmel')], max_length=240),
        ),
    ]
