# Generated by Django 3.1.2 on 2020-10-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbrewforyou_app', '0008_auto_20201008_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fav_breweries',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fav_breweries',
            field=models.ManyToManyField(blank=True, related_name='fav_breweries', to='microbrewforyou_app.Breweries'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fav_brewtypes',
            field=models.ManyToManyField(blank=True, related_name='fav_brewtypes', to='microbrewforyou_app.BrewTypes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
