# Generated by Django 3.1 on 2020-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbrewforyou_app', '0010_auto_20201012_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
